OLED_ENABLE = yes
EXTRAKEY_ENABLE = yes
MOUSEKEY_ENABLE = no
WPM_ENABLE = yes
ENCODER_ENABLE = no
CAPS_WORD_ENABLE = yes

LTO_ENABLE = yes

CONSOLE_ENABLE = no
COMMAND_ENABLE = no

SRC += features/layer_lock.c
